### ISSUE TITLE
Search not working for some reason.

### ISSUE THREAD

**Issue by ventz** [kaushalmodi/hugo-search-fuse-js#1]
Hi,

Tested this out with 3 themes. For some reason in neither of them it's working past search box input.

On hugo `v0.53`

Getting to:
```
http://localhost:1313/search/?q=welcome
```

But nothing is loading past that point - truly empty page.

For my config, I have tried:
```
theme = ["hugo-search-fuse-js", "beautifulhugo"]

and separately:

theme = ["hugo-search-fuse-js", "hyde-hyde"]
```

**Comment by kaushalmodi** [comment]
Hello,

Thanks for opening this issue.

I had the docs incomplete because I was lazy and didn't expect anyone else other than me to use this theme component.

I have now updated the README.org .. please see the 3rd point added there: https://github.com/kaushalmodi/hugo-search-fuse-js/blob/master/README.org

Let me know if you still have trouble getting the search to work.

**Comment by ventz** [comment]
@kaushalmodi Hi - I had the search already, however I didn't have hte outputs there -- but I did have them in the config config.toml as:

```
[outputs]
  home = ["HTML", "RSS", "JSON"]
```

But I just commented it out and added your suggested search.md.

Still no go :(

Tried it with the `nofancy` and `yinyang` themes too -- same thing.

It seems this theme is just a wrapped version of eddiewebb's steps: https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

I was having the same issue with his too. I am not sure if this is a "new hugo thing", or something else.

This is driving me crazy. I saw your threads/etc on the forums -- facing the same issue. Something so simple and yet so basic is not "built in". I agree it's a "theme add-on", but the way you are going about it is actually the smartest solution imo. A meta/abstract "theme" that you can apply on any existing theme. It's genius.

**Comment by kaushalmodi** [comment]
> but I did have them in the config config.toml as:

> [outputs]
>  home = ["HTML", "RSS", "JSON"]

`home` is a special page kind. It doesn't apply to any other page. So above wouldn't work. Look up "Page Kinds" in Hugo docs. 

>It seems this theme is just a wrapped version of eddiewebb's steps: https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

Yes, of course! I attribute this theme component to https://github.com/kaushalmodi/hugo-search-fuse-js/blob/master/static/js/search.js (credits in there .. I need to add credits to the README too). 

> Still no go :(

Can you share your site repo where you have attempted the steps in the updated README? May be looking at that will help me add stuff to the README that I took for granted. 

>Something so simple and yet so basic is not "built in".

There are many search libraries. So picking one as a built-in would be difficult. 

But please share your attempt at making this search component work, and I can help you further. 

You can see a minimal example of how to use this theme component here: https://github.com/kaushalmodi/hugo-bare-min-theme/tree/master/exampleSite.

Here is the search at work: https://hugo-bare-min.netlify.com/search/?q=Hugo

**Comment by ventz** [comment]
I created a new/clean site:

```
% hugo version
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
```

```
0.) cd /tmp

1.) hugo new site web

2.) cd web/themes
a.) git clone https://github.com/halogenica/beautifulhugo.git
NOTE: see issue here if you are using this theme and using "posts" (vs "post"):
https://github.com/halogenica/beautifulhugo/pull/241/files

b.) git clone https://github.com/kaushalmodi/hugo-bare-min-theme.git

3.) cd ../content/
# paste provided "search.md"

4.) cd ../
# add to 'config.toml':
theme = ["hugo-search-fuse-js", "beautifulhugo"]

# change in 'config.toml':
baseURL = "http://localhost:1313/"

5.) hugo server
```

Here is a copy of the full dir zipped up:
[web.zip](https://github.com/kaushalmodi/hugo-search-fuse-js/files/2771212/web.zip)

By the way, about:
> Yes, of course! I attribute this theme component to https://github.com/kaushalmodi/hugo-search-fuse-js/blob/master/static/js/search.js (credits in there .. I need to add credits to the README too).

^ meant it as in "if that one [his] doesn't work, assuming something has changed with hugo"

**Comment by kaushalmodi** [comment]
Thanks for that web.zip. 

The correct fix is https://github.com/halogenica/beautifulhugo/pull/244/files :)

But if the theme author rejects the PR, make this change locally to the `search.html` layout file:

```diff
diff --git a/layouts/_default/search.html b/layouts/_default/search.html
index 045dbb9..d2aa907 100644
--- a/layouts/_default/search.html
+++ b/layouts/_default/search.html
@@ -24,9 +24,7 @@
             </table>
         </small>
     </div></script>
-{{ end }}
 
-{{ define "footer" }}
 <script src={{ "js/libs/jquery/3.3.1/jquery.min.js" | absURL }}></script>
 <script src={{ "js/libs/fuse.js/3.2.1/fuse.min.js" | absURL }}></script>
 <script src={{ "js/libs/mark.js/8.11.1/jquery.mark.min.js" | absURL }}></script>
```

I verified that doing that makes the search like http://localhost:1313/search/?q=first work. Let me know how it goes for you.

**Comment by kaushalmodi** [comment]
@ventz Oh, and I have [updated the README too](https://github.com/kaushalmodi/hugo-search-fuse-js/blob/master/README.org#requirements) .. to take care of the stuff I took for granted :)

**Comment by kaushalmodi** [comment]
.. and the `hyde-hyde` theme [does not have the **main** block](https://github.com/htr3n/hyde-hyde/blob/ee52bb339cd2130d3cdf07288107ac07a42b2625/layouts/_default/baseof.html).

> A meta/abstract "theme" that you can apply on any existing theme.

So looks like that plan didn't work out in general 😛 . My main intention was to have a DRY theme component for all *my* sites, and this component served that purpose :).

**Comment by kaushalmodi** [comment]
@ventz So I should safely assume this issue as closed :)

**Comment by ventz** [comment]
@kaushalmodi Thank you so much!!

I am actually planning to fork off beautifulhugo and  because it seems the developer has not be merging quite a few fixes. There are many PRs/fixes, and I like the theme and plan on using it.

I need to read through the theme documentation (still new to hugo). For the most part everything has been very straight forward.

I am trying to understand the difference between these two:

```
{{ block "header" . }}{{ partial "header.html" . }}{{ end }}

vs

{{ partial "footer.html" . }}
{{ block "footer" . }}{{ end }}
```

What is the reason that the partial was not included in a "footer" block?

**Comment by kaushalmodi** [comment]
> What is the reason that the partial was not included in a "footer" block?

I did not want to break the original theme.

If I do this:

```
{{ partial "footer.html" . }}
{{ block "footer" . }}{{ end }}
```

both the partial and block are applied.

If I do this:

```
{{ block "footer" . }}
    {{ partial "footer.html" . }}
{{ end }}
```

the partial is applied as long as the footer block is not overridden by anything else. In the case of search.html, the footer define there will override the above block definition from baseof.html. So you would find stuff from the footer partial missing *only on* the search.html page (where the footer block got redefined).

I hope that makes sense.

**Comment by ventz** [comment]
Got it - thank you! (And thank you for all of the debugging/time here. Really appreciate it!)
